### ISSUE TITLE
How does the rounded corners plugin work?

### ISSUE THREAD

**Issue by tasmo** [ammen99/wayfire-plugins#2]
Wayfire crashes when I try to put it in plugins in the ini file.

**Comment by tasmo** [comment]
Found it!

It has nor interface an it must be spelled correctly.

Another issue with the plugin is, that it looks very crispy. And the 20px corners are way too large. I adjusted the radius dirtily which looked even worse.

**Comment by Caua77** [comment]
How to config this plugin ?

**Comment by Caua77** [comment]
> Found it!
> 
> It has nor interface an it must be spelled correctly.
> 
> Another issue with the plugin is, that it looks very crispy. And the 20px corners are way too large. I adjusted the radius dirtily which looked even worse.

How to config this plugin ?

**Comment by starsareintherose** [comment]
> > Found it!
> > It has nor interface an it must be spelled correctly.
> > Another issue with the plugin is, that it looks very crispy. And the 20px corners are way too large. I adjusted the radius dirtily which looked even worse.
> 
> How to config this plugin ?
```
plugins = \
  pulgin1 \
  plugin2 \
  rounded-corners
```

**Comment by ammen99** [comment]
The rounded corners plugin is intended to be a demo plugin for others interested in developing similar plugins, it is not really meant for end-users. Of course, feel free to use it if you like the current state, but it has way too many shortcomings in my opinion.
